/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pemilihan.dokter;

/**
 *
 * @author ACER E5-471
 */
public class Pemilihan extends javax.swing.JFrame {

    /**
     * Creates new form Pemilihan
     */
    public Pemilihan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            jPanel2 =(javax.swing.JPanel)java.beans.Beans.instantiate(getClass().getClassLoader(), "pemilihan/dokter.Pemilihan_jPanel2");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        spesial = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Dokter = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        usia = new javax.swing.JTextField();
        jenis = new javax.swing.JTextField();
        gol = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        kewar = new javax.swing.JTextField();
        waktu = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 153));
        setResizable(false);
        getContentPane().setLayout(null);

        spesial.setEditable(false);
        getContentPane().add(spesial);
        spesial.setBounds(220, 470, 150, 30);

        jLabel1.setFont(new java.awt.Font("Yu Mincho Light", 0, 36)); // NOI18N
        jLabel1.setText("PEMILIHAN DOKTER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 10, 390, 40);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 16)); // NOI18N
        jLabel2.setText("Dokter Spesialis");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 470, 140, 20);

        Dokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah Satu","DR.Farras Yassar", "DR.Anisa Putri", "DR.Harun Fajar" }));
        Dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DokterActionPerformed(evt);
            }
        });
        getContentPane().add(Dokter);
        Dokter.setBounds(220, 80, 150, 30);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 16)); // NOI18N
        jLabel3.setText("Pilih Dokter");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 80, 110, 20);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 16)); // NOI18N
        jLabel5.setText("Nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 150, 110, 20);

        jLabel6.setFont(new java.awt.Font("Segoe Print", 0, 16)); // NOI18N
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 190, 110, 20);

        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 16)); // NOI18N
        jLabel7.setText("Usia");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 230, 110, 20);

        jLabel8.setFont(new java.awt.Font("Segoe Print", 0, 16)); // NOI18N
        jLabel8.setText("Jenis Kelamin");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 270, 120, 20);

        jLabel9.setFont(new java.awt.Font("Segoe Print", 0, 16)); // NOI18N
        jLabel9.setText("Kewarganegaraan");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 390, 150, 20);

        jLabel10.setFont(new java.awt.Font("Segoe Print", 0, 16)); // NOI18N
        jLabel10.setText("Gol. Darah");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 310, 110, 20);

        jLabel11.setFont(new java.awt.Font("Segoe Print", 0, 16)); // NOI18N
        jLabel11.setText("Status");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 350, 110, 20);

        jLabel12.setFont(new java.awt.Font("Segoe Print", 0, 16)); // NOI18N
        jLabel12.setText("Waktu Praktek");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 430, 130, 20);

        nama.setEditable(false);
        getContentPane().add(nama);
        nama.setBounds(220, 140, 150, 30);

        alamat.setEditable(false);
        getContentPane().add(alamat);
        alamat.setBounds(220, 190, 150, 30);

        usia.setEditable(false);
        getContentPane().add(usia);
        usia.setBounds(220, 230, 150, 30);

        jenis.setEditable(false);
        getContentPane().add(jenis);
        jenis.setBounds(220, 270, 150, 30);

        gol.setEditable(false);
        getContentPane().add(gol);
        gol.setBounds(220, 310, 150, 30);

        status.setEditable(false);
        getContentPane().add(status);
        status.setBounds(220, 350, 150, 30);

        kewar.setEditable(false);
        getContentPane().add(kewar);
        kewar.setBounds(220, 390, 150, 30);

        waktu.setEditable(false);
        getContentPane().add(waktu);
        waktu.setBounds(220, 430, 150, 30);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 120, 340, 400);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(-10, 0, 460, 540);

        setBounds(0, 0, 463, 584);
    }// </editor-fold>//GEN-END:initComponents

    private void DokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DokterActionPerformed
        // TODO add your handling code here:
         if(Dokter.getSelectedItem().equals("DR.Farras Yassar")){ 
            nama.setText("DR. Farras Yassar "); 
            alamat.setText("Jl. Surabaya 16, Malang"); 
            usia.setText("20 Tahun"); 
            jenis.setText("Laki-Laki"); 
            gol.setText("A"); 
            status.setText("Belum Menikah "); 
            kewar.setText("Indonesia"); 
            spesial.setText("Dokter Umum"); 
            waktu.setText(" Pagi (07.00-15.00)"); 
        } 
        else 
        if(Dokter.getSelectedItem().equals("DR.Anisa Putri")){ 
            nama.setText("DR. Anisa Putri"); 
            alamat.setText("Jl. Veteran 3, Malang"); 
            usia.setText("20 Tahun"); 
            jenis.setText("Perempuan"); 
            gol.setText("O"); 
            status.setText("Belum Menikah"); 
            kewar.setText("Indonesia"); 
            spesial.setText("Dokter Gigi"); 
            waktu.setText(" Sore (16.00-22.00)"); 
        } 
        else 
        if(Dokter.getSelectedItem().equals("DR.Harun Fajar")){ 
            nama.setText("DR. Harun Fajar "); 
            alamat.setText("Jl. Bandung 9, Malang"); 
            usia.setText("20 Tahun"); 
            jenis.setText("Laki-Laki"); 
            gol.setText("B"); 
            status.setText("Belum Menikah"); 
            kewar.setText("Indonesia"); 
            spesial.setText("Dokter Gizi"); 
            waktu.setText(" Malam (22.00-06.00)"); 
        } 
    
    }//GEN-LAST:event_DokterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemilihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemilihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemilihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemilihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemilihan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Dokter;
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField gol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jenis;
    private javax.swing.JTextField kewar;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField spesial;
    private javax.swing.JTextField status;
    private javax.swing.JTextField usia;
    private javax.swing.JTextField waktu;
    // End of variables declaration//GEN-END:variables
}
