/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pemilihan.dokter;

/**
 *
 * @author ACER E5-471
 */
public class Penerbangan extends javax.swing.JFrame {

    /**
     * Creates new form Penerbangan
     */
    public Penerbangan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tujuan = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        mas1 = new javax.swing.JTextField();
        jam1 = new javax.swing.JTextField();
        jam2 = new javax.swing.JTextField();
        mas2 = new javax.swing.JTextField();
        jam3 = new javax.swing.JTextField();
        mas3 = new javax.swing.JTextField();
        jam4 = new javax.swing.JTextField();
        mas4 = new javax.swing.JTextField();
        jam5 = new javax.swing.JTextField();
        mas5 = new javax.swing.JTextField();
        jam6 = new javax.swing.JTextField();
        mas6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel1.setText("Jadwal Penerbangan Abdurahman Saleh");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 0, 380, 40);

        tujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Tujuan-", "Jakarta", "Surabaya", "Semarang", "Bali", " " }));
        tujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuanActionPerformed(evt);
            }
        });
        getContentPane().add(tujuan);
        tujuan.setBounds(70, 50, 140, 30);

        jLabel16.setText("Maskapai");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(110, 90, 120, 20);

        jLabel15.setText("Jam Penerbangan");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(330, 90, 140, 20);

        mas1.setEditable(false);
        getContentPane().add(mas1);
        mas1.setBounds(310, 120, 210, 30);

        jam1.setEditable(false);
        getContentPane().add(jam1);
        jam1.setBounds(40, 120, 210, 30);

        jam2.setEditable(false);
        getContentPane().add(jam2);
        jam2.setBounds(40, 170, 210, 30);

        mas2.setEditable(false);
        getContentPane().add(mas2);
        mas2.setBounds(310, 170, 210, 30);

        jam3.setEditable(false);
        getContentPane().add(jam3);
        jam3.setBounds(40, 220, 210, 30);

        mas3.setEditable(false);
        getContentPane().add(mas3);
        mas3.setBounds(310, 220, 210, 30);

        jam4.setEditable(false);
        getContentPane().add(jam4);
        jam4.setBounds(40, 270, 210, 30);

        mas4.setEditable(false);
        getContentPane().add(mas4);
        mas4.setBounds(310, 270, 210, 30);

        jam5.setEditable(false);
        getContentPane().add(jam5);
        jam5.setBounds(40, 320, 210, 30);

        mas5.setEditable(false);
        getContentPane().add(mas5);
        mas5.setBounds(310, 320, 210, 30);

        jam6.setEditable(false);
        getContentPane().add(jam6);
        jam6.setBounds(40, 370, 210, 30);

        mas6.setEditable(false);
        getContentPane().add(mas6);
        mas6.setBounds(310, 370, 210, 30);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 550, 500);

        setBounds(0, 0, 565, 536);
    }// </editor-fold>//GEN-END:initComponents

    private void tujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuanActionPerformed
        // TODO add your handling code here:
        if(tujuan.getSelectedItem().equals("Jakarta")){

            jam1.setText("Garuda Indonesia");
            mas1.setText("05.00");

            jam1.setText("Air Asia");
            mas2.setText("09.09");
            jam2.setText("Lion Air");
            mas3.setText("10.00");

            jam2.setText("Garuda Indonesia");
            mas4.setText("12.00");
            jam3.setText("Lion Air");
            mas5.setText("10.09");

            jam3.setText("Batik Air");
            mas6.setText("11.09");
            jam4.setText("Garuda Indonesia");
            mas6.setText("01.01");
            jam5.setText("Air Asia");
            mas5.setText("11.00");
            jam6.setText("Citilink");
            mas6.setText("12.08");

          

        }
        else
        if(tujuan.getSelectedItem().equals("Surabaya")){
             jam1.setText("Kalstar Aviation");
            mas1.setText("15.30");

            jam1.setText("Batavia");
            mas2.setText("19.50");
            jam2.setText("Lion Air");
            mas3.setText("11.10");

            jam2.setText("Garuda Indonesia");
            mas4.setText("12.00");
            jam3.setText("AOC 121");
            mas5.setText("03.18");

            jam3.setText("Batik Air");
            mas6.setText("09.10");
            jam4.setText("Garuda Indonesia");
            mas6.setText("02.10");
            jam5.setText("Batik Air");
            mas5.setText("12.01");
            jam6.setText("Aviastar");
            mas6.setText("05.09");
        }
        else
        if(tujuan.getSelectedItem().equals("Semarang")){

            jam1.setText("Garuda Indonesia");
            mas1.setText("05.00");

            jam1.setText("Batavia Air");
            mas2.setText("10.10");
            jam2.setText("Air Asia");
            mas3.setText("10.11");

            jam2.setText("Citilink");
            mas4.setText("13.09");
            jam3.setText("Sriwijaya Air");
            mas5.setText("16.10");

            jam3.setText("Batik Air");
            mas6.setText("09.56");
            jam4.setText("Transnusa");
            mas6.setText("06.05");
            jam5.setText("NAM Air");
            mas5.setText("17.10");


        }
        else if
        (tujuan.getSelectedItem().equals("Bali")){
             jam1.setText("Wings Air");
            mas1.setText("10.09");

            jam1.setText("Air Asia");
            mas2.setText("23.18");
            jam2.setText("Sriwijaya AIr");
            mas3.setText("12.08");

            jam2.setText("Mandala Tigerair");
            mas4.setText("14.06");
            jam3.setText("Lion Air");
            mas5.setText("14.15");

            jam3.setText("Batik Air");
            mas6.setText("14.09");
            jam4.setText("Sky AViation");
            mas6.setText("10.45");
            jam5.setText("Susi Air");
            mas5.setText("10.12");

        }
    }//GEN-LAST:event_tujuanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penerbangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penerbangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penerbangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penerbangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penerbangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jam1;
    private javax.swing.JTextField jam2;
    private javax.swing.JTextField jam3;
    private javax.swing.JTextField jam4;
    private javax.swing.JTextField jam5;
    private javax.swing.JTextField jam6;
    private javax.swing.JTextField mas1;
    private javax.swing.JTextField mas2;
    private javax.swing.JTextField mas3;
    private javax.swing.JTextField mas4;
    private javax.swing.JTextField mas5;
    private javax.swing.JTextField mas6;
    private javax.swing.JComboBox<String> tujuan;
    // End of variables declaration//GEN-END:variables
}
